version: '3'

services:
  database:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: pr4_database
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db4_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

    # healthcheck:
    #   test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    #   timeout: 1s
    #   retries: 10

    ports:
      - "9906:3306"

  php-apache:
    build: .
    ports:
      - "9090:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/apache2:/var/log/apache2
    links:
      - database
    # depends_on:
    #   db:
    #     condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "9099:80"
    volumes: 
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php-apache
    # depends_on:
    #   php-apache:

volumes:
  db4_volume:

